---
roles:
  - name: wazuh.wazuh_agent
    version: "4.14.2"         # Pin to Wazuh version

collections:
  - name: checkmk.general
    version: ">=4.0.0"        # Minimum version
  - name: ansible.posix
    version: ">=1.5.0"
